# Generated by Django 5.2.5 on 2025-08-16 08:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0003_alter_staff_branch_fk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='staff',
            field=models.ForeignKey(blank=True, limit_choices_to={'status': 'active'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_profile', to='companies.staff'),
        ),
    ]
