# Generated by Django 5.2.5 on 2025-08-16 08:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0004_alter_userprofile_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fieldschedule',
            name='staff',
            field=models.ForeignKey(blank=True, db_column='StaffCode', limit_choices_to=models.Q(('status__iexact', 'active'), ('status', '1'), ('status', 1), ('status', True), _connector='OR'), null=True, on_delete=django.db.models.deletion.SET_NULL, to='companies.staff', to_field='staffcode'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='staff',
            field=models.ForeignKey(blank=True, limit_choices_to=models.Q(('status__iexact', 'active'), ('status', '1'), ('status', 1), ('status', True), _connector='OR'), null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_profile', to='companies.staff'),
        ),
    ]
